### ISSUE TITLE
Allow users to access the same GOCDB account either via X.509 certificates or via the EGI SSO

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#170]
Atleast two users of GOCDB ([user 1](https://ggus.eu/index.php?mode=ticket_info&ticket_id=142275) and myself) think it would be beneficial to be able to access the same GOCDB account via both X.509 certificates and EGI SSO.

It looks like this may have been half implemented already. 

There is already a [script](https://github.com/GOCDB/gocdb/blob/dev/resources/QueryPopulateSSO_UsernameRunner.php) that maps DN based users to their EGI SSO usernames (if their EGI SSO account has had a certificate [linked](https://wiki.egi.eu/wiki/AAI_usage_guide#Linking_your_Certificate_to_your_EGI_Account) to it) in the database (in the `Username1` field of the [`User`](https://github.com/GOCDB/gocdb/blob/dev/lib/Doctrine/entities/User.php) entity).

But it seems that `Username1` is [used sparingly](https://github.com/GOCDB/gocdb/search?q=Username1) and when I access GOCDB with my EGI SSO account it doesn’t map to my certificate account.

**Comment by gwarf** [comment]
For the record, when people are coming from EGI Check-in it shouldn't be assumed they will use EGI SSO (and in fact EGI SSO is supposed to be deprecated by Check-in as it was some kind of catch-all IdP, now with Check-in users can user their institution IdP).
Also EGI Check-in does include an IGTF IdP allowing any user to log-in via Check-in, independently from their usual IdP.
And using Check-in users can link their identities together (like linking their institution account, with their IGTF IdP account as well as linking with a social media account). And once done all those accounts will appear as the same one for the service providers: https://wiki.egi.eu/wiki/AAI_usage_guide#Linking_Additional_Organisational.2FSocial_Identities_to_your_EGI_Account
My point is that you may want to rely on Check-in to manage identity linking instead of implementing it yourself. And ideally in that scenario Check-in should be the only entry point, direct authentication via certificate could be avoided and simplify the management on your side.

**Comment by gregcorbett** [comment]
Just assigning ElliottKasoar as this will be solved by the identity linking work.

**Comment by gregcorbett** [comment]
> Just assigning ElliottKasoar as this will be solved by the identity linking work.

And indeed this was solved in #294.
