### ISSUE TITLE
Allow UI "views" driven by URL-specific configuration.

### ISSUE THREAD

**Issue by ineilson** [GOCDB/gocdb#216]
Allow the UI to be modified based on alternate configuration options keyed on the access URL used.

**Comment by gregcorbett** [comment]
A question and a statement that might form future issues.

- Does the code in #215 allow for renaming ServiceGroups (in menus etc)?
- I guess because the landing page is completely static, if we wanted URL based landing pages it would be a matter of either making the current one dynamic (or serving up different static pages based on a URL...)

**Comment by ineilson** [comment]
> * Does the code in #215 allow for renaming ServiceGroups (in menus etc)?

Yes and no, in as much as it allows retrieval of a name mapping, via the config service ->getNameMapping(...), which must then be coded into the relevant view.

**Comment by ineilson** [comment]
> * I guess because the landing page is completely static, if we wanted URL based landing pages it would be a matter of either making the current one dynamic (or serving up different static pages based on a URL...)

Agreed.

**Comment by gregcorbett** [comment]
I'm going to track some next step features here for now - because #215 is going on for two long. Probably they'll become separate issues after that PR gets merge.

- extend renaming to "ServiceGroup".
- pre filter by scope on ServiceGroup page where/when appropriate
- downtime calendar view differs between URL view and default view when no scope is selected and "Fetch Downtimes" clicked i.e. `hostname/portal/index.php?Page_Type=Downtimes_Calendar&view=basicWeek` vs `magic_url/portal/index.php?Page_Type=Downtimes_Calendar&view=basicWeek`
