### ISSUE TITLE
Some scope pages fail to return any content

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#67]
e.g. https://goc.egi.eu/portal/index.php?Page_Type=Admin_Scope&id=2

**Comment by davidmeredith** [comment]
This occurs when trying to view the EGI scope tag (id=2) and because EGI is the default scope, too many resources are selected and we get out of mem issue: 

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 115 bytes) in /usr/share/gocdbGit/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2727, referer: https://goc.egi.eu/portal/index.php?Page_Type=Admin_Scopes

**Comment by gregcorbett** [comment]
"went away" when we moved infrastructures.
